// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/go-redis/redis/v8"
	"github.com/gopperin/sme-delay-service/internal/domain/base"
	"github.com/gopperin/sme-delay-service/internal/domain/delay"
	"github.com/nsqio/go-nsq"
)

// Injectors from wire.go:

// InitBaseAPI init base api wire
func InitBaseAPI() base.API {
	service := base.ProvideService()
	api := base.ProvideAPI(service)
	return api
}

// InitDelayAPI init base api wire
func InitDelayAPI(p *nsq.Producer, redis2 *redis.Client) delay.API {
	service := delay.ProvideService(p, redis2)
	api := delay.ProvideAPI(service)
	return api
}
